In [1]:
import numpy as np 

In [2]:
arr=np.array([1,3,4])
arr

array([1, 3, 4])

In [3]:
arr.ndim

1

In [4]:
x=np.arange(1,10,1)
x

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
y=np.linspace(1,2,5)
y

array([1.  , 1.25, 1.5 , 1.75, 2.  ])

In [6]:
z=np.logspace(2,4,3)
z

array([  100.,  1000., 10000.])

In [7]:
# np.zeros ->gives arry full of zeros

p=np.zeros(5)
p


array([0., 0., 0., 0., 0.])

In [8]:
e=np.zeros([3,3])
e

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [9]:
#np.ones
w=np.ones([3,5], dtype=int) # default dtype is float
w

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [10]:
#full 
arr=np.full([2,4], 5) # the parameters are ,[dimension], default value to fill 
arr

array([[5, 5, 5, 5],
       [5, 5, 5, 5]])

In [11]:
#np.empty -> create empty array
arr=np.empty([3,4])
arr

array([[1.05198605e-311, 3.16202013e-322, 0.00000000e+000,
        0.00000000e+000],
       [1.21190256e-305, 4.76763527e-038, 2.36256606e+180,
        4.98775879e-037],
       [4.66377447e-033, 3.14328049e+179, 1.56333803e+185,
        3.40597876e-057]])

In [12]:
arr=np.random.rand(10)
arr
#here it creates it like single list of 10 random values


array([0.16227732, 0.41875801, 0.29036054, 0.32252209, 0.94308991,
       0.80664639, 0.36180602, 0.51418411, 0.01351897, 0.38121946])

In [13]:
arr=np.random.rand(2,3) #yha pe humne dimension bhi de diye 
arr

array([[0.53908567, 0.95016606, 0.82905916],
       [0.96985803, 0.63990425, 0.10574393]])

In [14]:
arr=np.random.randn(2,2) # normaly distributed from a sandard normal distribution
arr


array([[-1.10422288,  1.29387195],
       [-0.22098807,  0.15572885]])

In [15]:
arr=np.random.randint(23,56, size=(2,4)) #start,stop, no of random no. or dimension
arr

array([[35, 31, 33, 34],
       [26, 45, 33, 54]], dtype=int32)

# Numpy datatypes and typecasting 
by default if there are mulitple dtypes of elements in the input array ,list , then the dtype of the nparry will the data type which has heighest space 

In [16]:
arr=np.array([2,4,5,6,87,2])
arr.dtype

dtype('int64')

In [17]:
arr=np.array([3,5,6,7],dtype=np.float64)
arr.dtype

dtype('float64')

In [18]:
#typecasting

arr=np.array([2,35,6,7,37,67])
arr.dtype
new_ar=arr.astype(np.float64)
new_ar.dtype


dtype('float64')

In [19]:
new_ar2=new_ar.astype(np.int32)
new_ar2.dtype


dtype('int32')

## Reshaping the array


In [20]:

#reshape

arr=np.array([1,2,3,4,5,6])
reshaped=arr.reshape(2,3)
print(reshaped)


[[1 2 3]
 [4 5 6]]


# Ravel 
 the ravel is used to convert a multidimensional arry into one dimensional arry
 

In [21]:
raveled=reshaped.ravel()
raveled

array([1, 2, 3, 4, 5, 6])

# Flatten 
the flatten also does the same as ravel but their is very key and important difference in what they do with the data/arry

the ravel creates a view of the array so any changes made to the raveled arr will also reflect on the reshaped 

like if we do 

ravel[100]=something 
then 
reshaped[100] will also become something

Now you can see the problem right 

so to solve this problem we have flatten 





In [22]:
flat=reshaped.flatten()
flat

array([1, 2, 3, 4, 5, 6])

## Arithmatic operations


In [23]:
a=np.array([[2,3,5],[3,5,7]])
b=np.array([[2,6,7],[2,35,6]])
print(a+b)

[[ 4  9 12]
 [ 5 40 13]]


In [24]:
print(a-b)

[[  0  -3  -2]
 [  1 -30   1]]


In [25]:
print(a*b)

[[  4  18  35]
 [  6 175  42]]


In [26]:

print(a//b)

[[1 0 0]
 [1 0 1]]


In [27]:
print(a%b)

[[0 3 5]
 [1 5 1]]


In [28]:
print(a**2)
#it returns the A^2


[[ 4  9 25]
 [ 9 25 49]]


## Universal function -> ufuncs


In [29]:
print(np.sqrt(arr))

[1.         1.41421356 1.73205081 2.         2.23606798 2.44948974]


In [30]:
print(np.exp([1,3]))

[ 2.71828183 20.08553692]


In [31]:
sined=np.array([0,np.pi, np.pi/2])
print(np.sin(sined))

[0.0000000e+00 1.2246468e-16 1.0000000e+00]


# Indexing and slicing
it has same kind of indexing and slicing similar to other list/strig dtypes

In [32]:
arr=np.array([20,495,693,96,39])
arr[1::2]

array([495,  96])

# np.take 
 it is a built in function which takes the arr and the  index to find the exact element 
 

In [33]:
arr=np.random.randint(0,10,size=(3,4))
arr

array([[7, 9, 3, 0],
       [0, 3, 5, 1],
       [5, 6, 1, 8]], dtype=int32)

In [34]:
index=[7]
print(np.take(arr,index))
#take note that in numpy the elements are numbered one after the other

[1]


# Iterations 
np.nditer(arr)
np.ndenumerate(arr) just like in normal enumerate funciton it will give index value pair 

In [35]:
for x in np.nditer(arr):
    print(x, end=" ")


7 9 3 0 0 3 5 1 5 6 1 8 

In [36]:
for x in np.ndenumerate(arr):
    print(x)

((0, 0), np.int32(7))
((0, 1), np.int32(9))
((0, 2), np.int32(3))
((0, 3), np.int32(0))
((1, 0), np.int32(0))
((1, 1), np.int32(3))
((1, 2), np.int32(5))
((1, 3), np.int32(1))
((2, 0), np.int32(5))
((2, 1), np.int32(6))
((2, 2), np.int32(1))
((2, 3), np.int32(8))


## views vs copies

view me any change to the view arry will also change the original arry
view=arr
now if we do 
view[0]=22
then 
arr[0] will also become 22

but in case of copy it will not reflect the changes as copy creates a total new arr

arrc=np.copy(arr)
arrc[0]=22
will not affect the original arr

arr[0]==original value


In [37]:
#copy
arr= np.random.randint(0,10,size=(2,3))
arrc=np.copy(arr)
arrc[0][0]=22
print(arr)
print(arrc)

[[7 5 6]
 [8 9 5]]
[[22  5  6]
 [ 8  9  5]]


In [38]:
#view 
arr= np.random.randint(0,10,size=(2,3))
arrc=arr
arrc[0][0]=22
print(arr)
print(arrc)

[[22  5  8]
 [ 0  8  1]]
[[22  5  8]
 [ 0  8  1]]


# Transpose of matrix

In [39]:
print(arr.transpose())

[[22  0]
 [ 5  8]
 [ 8  1]]


# Swapaxes 
it swap 2 specific axes in the materix

In [40]:
swap=np.swapaxes(arr,0,1) #swaping o and 1 axes
print(swap)
print(arr.shape)
print(swap.shape)

[[22  0]
 [ 5  8]
 [ 8  1]]
(2, 3)
(3, 2)


## Concat
np.concatenate
# Note :
ValueError: all the input array dimensions except for the concatenation axis must match exactly

In [41]:
a=np.random.randint(1,10,size=(2,2))
b=np.random.randint(2,10,size=(2,2))
combined=np.concatenate((a,b))
print(a)
print(b)
print(combined)
print(combined.shape)

[[3 3]
 [7 5]]
[[2 6]
 [4 8]]
[[3 3]
 [7 5]
 [2 6]
 [4 8]]
(4, 2)


In [42]:
combine=np.hstack((a,b)) #concate hroizontally 
print(combine)
print(combine.shape)

[[3 3 2 6]
 [7 5 4 8]]
(2, 4)


In [43]:
combine1=np.vstack((a,b)) #concate vertically 
print(combine1)
print(combine1.shape)

[[3 3]
 [7 5]
 [2 6]
 [4 8]]
(4, 2)


In [44]:
# this can be also done with the above concatenate function as well instead of using the 
# hstack or the vstack 

combine=np.concatenate((a,b),0) # here we are also giving the axes for concat , 0->horizontal and 1-> vertical axes
print(combine)
print(combine.shape)

[[3 3]
 [7 5]
 [2 6]
 [4 8]]
(4, 2)


In [45]:
combine_1=np.concatenate((a,b),1)
print(combine_1)
print(combine_1.shape)

[[3 3 2 6]
 [7 5 4 8]]
(2, 4)



## Spliting the array/matrix now
now before spliting check that wether that kind of equally split is possible or not



In [46]:
print(np.hsplit(a,2))

[array([[3],
       [7]], dtype=int32), array([[3],
       [5]], dtype=int32)]


In [47]:
print(np.vsplit(a,2))

[array([[3, 3]], dtype=int32), array([[7, 5]], dtype=int32)]


## Repeat 
np.repeat(arr, times)


In [48]:
x=np.array([1,3,45,6])
print(np.repeat(arr,3))

[22 22 22  5  5  5  8  8  8  0  0  0  8  8  8  1  1  1]


## Aggregate functions
np.mean()
np.sum()
np.std()
np.median()
np.var()
np.min()
np.max()


In [49]:
#incase i want to find these along some particular axes then we can also specify that too
matrix=np.random.randint(0,10,size=(2,3))
print(matrix,end="\n")
print(np.sum(matrix, axis=0)) # 0 for column wise and one for row wise

[[4 0 0]
 [8 6 7]]
[12  6  7]


## Cumulative Operation -> running total
so if arr=[2,3,5,6]
then np.cumsum(arr)=[2,5,10,16] basically cumulative sum le raha hai

In [50]:
print(np.cumsum(matrix))

[ 4  4  4 12 18 25]


In [51]:
print(np.cumprod(matrix))

[4 0 0 0 0 0]


## Conditional based choices
# Where


In [52]:
result=np.where(arr<2,"low","high") #so what this does is that it prints low where value in arr is less than 2 and high in place where the value is greater thant 2
print(result)

[['high' 'high' 'high']
 ['low' 'high' 'low']]


# Argwhere : row-column position for 2d arrays 

In [53]:
print(matrix)
print("   ")
print(np.argwhere(matrix<3)) #this returns the [row,column] for values that are put in the condition


[[4 0 0]
 [8 6 7]]
   
[[0 1]
 [0 2]]


In [54]:
mask=np.logical_and(matrix>2,matrix<7)
mask

array([[ True, False, False],
       [False,  True, False]])

In [55]:
mask=np.logical_or(matrix>2,matrix<7)
mask

array([[ True,  True,  True],
       [ True,  True,  True]])

## Broadcasting
streching or array to perform operation with arrys who do no have same shape 

what broadcasting does is 

Step 1 :  the operation is possible only if both have same shape 
incase shape is not same and the shape has 1 in it 
note if the shape doesn't have 1 then the operation  is not possible 

suppose arr1=[2,4,6] and arr2=[5]
now what happens in stretching is that the arr2 becomes something thant matches the shape of  the bigger array

arr2 become [5,5,5] 

 now the operation is performed

In [56]:
image=np.array([[2,4],[3,5]])
image.shape
brightness=image+50
brightness

array([[52, 54],
       [53, 55]])

## Vectorization
np.vectorize(fn)
what is does is vectorize the function given int  the parameter for the any arry operation


In [57]:
def fuckitup(x):
    return x+3
vfun=np.vectorize(fuckitup)

print(vfun(matrix))

[[ 7  3  3]
 [11  9 10]]


## Dealing with missing values
np.nan -> not number
np.inf and -np.inf , to give infinite values

In [58]:
''' np.isnan
    np.isinf
    np.isfinite

    these are used to to detect any null values, infinite value or finite value'''

new=np.nan_to_num(b) #what this does is that i changes the nan to 0 and positive ,neg infintes to 1 and -1 respectively



## shorthands 
np.c_[matrix1, matrix2]
note : it only contcatenates along the the axis=1 so that would mean that it adds another column to it , if we were using a diffrent like matrices instead of single arrays


In [64]:
x=np.array([2,4,5,6])
y=np.array([3,56,2,6])
z=np.c_[x,y]
z

array([[ 2,  3],
       [ 4, 56],
       [ 5,  2],
       [ 6,  6]])